services:
  greenwebsite:
    build:
      context: .
    restart: unless-stopped
    environment:
      NODE_ENV: production
    ports:
      - 3020:3000
#    volumes:
#      - ./prisma/:/app/prisma/
#      - ./uploads/:/app/uploads/
