import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ClientScripts from "./_layout-compoents/ClientScripts";
import { NavBar } from "./_layout-compoents/Nav";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
        {/* <link rel="stylesheet" href="/aos/aos.css" /> */}
      </head>
      <body className={inter.className}>
        <div className="flex flex-col overflow-hidden min-h-screen">
          <NavBar />
          <div className="grow">
            {children}
          </div>
          <Footer />
        </div>
        <ClientScripts />
      </body>
    </html >
  );
}
function Footer() {
  return <footer className="bg-gray-200 text-slate-400 text-center py-5">
    <p>© 2021 Green Agricorp</p>
  </footer>
}
