import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { LineChart, Mail, MenuIcon } from "lucide-react"
import { NavBar } from "./_layout-compoents/Nav";
import Script from "next/script";
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
      </head>
      <body className={inter.className}>
        <div className="flex flex-col overflow-hidden min-h-screen">
          <NavBar />
          <div className="grow">
            {children}
          </div>
          <Footer />
        </div>
        <Script src="https://unpkg.com/aos@next/dist/aos.js" />
        <Script src="/script/aos_init.js"></Script>
      </body>
    </html >
  );
}
function Footer() {
  return <footer className="bg-emerald-600 text-white text-center py-5">
    <p>© 2021 Green Agricorp</p>
  </footer>
}
